#!/command/with-contenv bash

source /assets/functions/00-container

SERVICE_NAME="n8n"

check_container_initialized
check_service_initialized init

liftoff

print_start "Starting n8n ${N8N_VERSION}"
exec n8n start
